import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'

export default function Home() {
  return (
    <>
      <Head>
        <title>Joshua U's Portfolios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className=" bg-gray-300 min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl" font-burtons>Joshua U</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl"/></li>
              <li><a className="bg-cyan-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
              <li></li>
            </ul>
            </nav>
            <div className="text-center p-10 py-10">
              <h2 className="text-5xl text-green-900 font-medium">Joshua Usselman</h2>
              <h3 className="text-2xl py-2">Developer and Educator</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
             
            </div>
        </section>
      </main>
    </>
  )
}
